### ISSUE TITLE
i want to use orientdb with php but get connecting error

### ISSUE THREAD

**Issue by AhsanAbrar** [Ostico/PhpOrient#101]
Fatal error: Uncaught PhpOrient\Exceptions\SocketException: socket_read(): unable to read from socket [104]: Connection reset by peer in D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php:147 Stack trace: #0 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php(94): PhpOrient\Protocols\Binary\OrientSocket->read(2) #1 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(146): PhpOrient\Protocols\Binary\OrientSocket->connect() #2 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\Abstracts\Operation.php(76): PhpOrient\Protocols\Binary\SocketTransport->getSocket() #3 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(223): PhpOrient\Protocols\Binary\Abstracts\Operation->__construct(Object(PhpOrient\Protocols\Binary\SocketTransport)) #4 D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(161): PhpOrient\Protocols\Binary\SocketTransport->operationFactory('PhpOrient\\Proto...', Array) #5 D:\laragon\www\PhpOrient in D:\laragon\www\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php on line 147

what mean of this error?

**Comment by andreyvk** [comment]
Hi, It means that your connection timed out.

**Comment by AhsanAbrar** [comment]
but what's the solution?

i love to use OrientDB but it's not working with PHP :(

so now i'm trying to use neo4j because it's working fine with Laravel PHP

OrientDB Team should improve their PHP driver too.

**Comment by Ostico** [comment]
Hi @AhsanAbrar ,
the error you got `unable to read from socket [104]: Connection reset by peer` means that your PHP can not connect with your OrientDB database, it is a connection issue, the server refused the connection. Maybe do you have a firewall or you configured the wrong port/ip in your php.
Otherwise, ensure that OrientDB is up and running.

To have a better support, please provide me more info, like some snippet of code to reproduce the error and your configuration.

It's difficult to imagine that such error can be caused by a bug in PHPOrient and never reported by the community that use it, because i suppose you are not the only one who use it.

Anyway, just to explain, the PHP driver is open source and it's development is not ( and never been ) sponsored in any way by the OrientDB team.

Feel free to contribute to improve it.

**Comment by AhsanAbrar** [comment]
`<?php

require "vendor/autoload.php";

use PhpOrient\PhpOrient;

$client = new PhpOrient();
$client->hostname = 'localhost';
$client->port     = 2480;
$client->username = 'root';
$client->password = 'root';

var_dump($client->dbList());

?>`

here is the code for index.php

i'm not sure what's wrong with me.

i'm using php 7.2
laragon server using: https://laragon.org/
