### ISSUE TITLE
int is returned as string 

### ISSUE THREAD

**Issue by zifnab87** [Ostico/PhpOrient#14]
dev-master:today
Hi, I am inserting an int and it is returned as a string. Here is my schema setup (it is integer obviously and saved): http://i.imgur.com/vc93Yq6.png
```php
$data = ["IsOfTypeCount" => 10];
var_dump($data);
$transaction = $db->getTransactionStatement();
$transaction = $transaction->begin();
$record =  (new Record())
            ->setOData( $data )
            ->setOClass( "Entity" )
            ->setRid( new ID() );

$createCommand = $db->recordCreate($record);
$transaction->attach( $createCommand );
$transaction->commit();
$record = $db->query("select from Entity where @rid ='".$record->getRid()."'")[0];
$dataNew = $record->getOData();
 var_dump($dataNew);
```
```php
//results:
array(1) {
  ["IsOfTypeCount"]=>
  int(10)
}
array(1) {
  ["IsOfTypeCount"]=>
  string(2) "10"
}
```

Thanks 
Michail

**Comment by Ostico** [comment]
Hi @zifnab87 ,
this is normal if you are using a 32bit version of PHP.
On 32bit version of PHP or on a 32bit Operating system PhpOrient treat integers as string to avoid data loss because PHP can't handle 64bit integers without loss of significant digits. 

https://github.com/Ostico/PhpOrient#warning-if-you-use-a-32bit-platform-you-must-use-one-of-these-libraries-into-your-application-to-avoid-the-loss-of-significant-digits-with-java-long-integers-furthermore-these-php-modules-should-be-loaded-to-achieve-better-driver-performances-on-these-systems

https://github.com/Ostico/PhpOrient/blob/master/src/PhpOrient/Protocols/Binary/Serialization/CSV.php#L230

If you are not using a 32bit version of PHP surely it is a bug. 
This is an easy test:
```php
var_dump( PHP_INT_SIZE == 4 );
# in your system i'm expecting true
```

Let me know.

**Comment by zifnab87** [comment]
@Ostico Thanks for the quick reply! The code above returns true :)

**Comment by Ostico** [comment]
For data consistency on 32bit platform i prefer to maintain everithing as string, alternatively every user should guess if the type of the data is "string/INT".

Moreover, if you use Java, or if you connect to a pre-existent database filled with data from other languages, you could have data loss or corrupt the database data.

**Comment by zifnab87** [comment]
Thanks again! Is there a way or will there be a way for me to know what orientdb type is each record property so I can safely cast it if I need to? I am in a migration process from Neo4j and all my json-schema validators in the client side are broken for all the ints

**Comment by Ostico** [comment]
With 64bit systems/build all types are correctly managed as INT 64bit. BCMath and GMP should be used on every php 32bit installation because they are much faster than php native implementation i made. They are Arbitrary Precision Mathematics, they treat int as strings so the 32bit systems can handle 64bit Long numbers.

At the high level there is not possibility at the moment to know wich type of field we are handling (float/long/int/short).

**Comment by zifnab87** [comment]
Thank you! I am closing the issue. I decided to try casting it and if there will be precision loss I send the propertyName_str and unset the other one (propertyName) back to the client
