### ISSUE TITLE
Handling insert / update error

### ISSUE THREAD

**Issue by bankorh** [Ostico/PhpOrient#18]
Hi.

Recently I faced some issues of inserting / updating a unique key. I created an index and set it to unique. Whenever I try to insert the duplicated key, I got the exception error.

I would like to ask, is it possible to get something like status code that representing the error like "key is existing"?

**Comment by Ostico** [comment]
Hi @bankorh ,

at the moment there are not a error code map, basically because OrientDB at moment does not pass codes but only exceptions. Surely i can try to add a map of error codes, but they would be totally arbitrary, and if you will rely on them, when OrientDB will implement it's own codes there will be a mismatch. Before implement that solution i must discuss with OrientDb Team.

**Comment by bankorh** [comment]
Hi, @Ostico ,

thank you for your reply and your contribution for this. Looking for better solutions from you. Have a nice day.
