### ISSUE TITLE
Record ID returned as decimal

### ISSUE THREAD

**Issue by emman-ok** [Ostico/PhpOrient#65]
How Do I Solve This rid: "#13:25.0000000000".
Was Expecting rid:"13:25"

**Comment by andreyvk** [comment]
That doesnt look good. Any way to reproduce that?

**Comment by smolinari** [comment]
@emman-ok - Is the problem solved? If yes, what was the solution?

Scott

**Comment by emman-ok** [comment]
Yes , I just have to edit the file path "PhpOrient\src\PhpOrient\Protocols\Binary\Data\ID.php" by casting the cluster and position into integer

public function __construct( $cluster = -1, $position = -1 ) {
        if ( is_array( $cluster ) ) {
            if ( isset( $cluster[ 'cluster' ] ) ) {
                $this->cluster = (int)$cluster[ 'cluster' ];
            }
            if ( isset( $cluster[ 'position' ] ) ) {
                $this->position = (int)$cluster[ 'position' ];
            }
        } else {
            if ( is_string( $cluster ) && $cluster[ 0 ] === '#' ) {
                list( $this->cluster, $this->position ) = self::parseString( $cluster );
            } else {
                $this->cluster  = (int)$cluster;
                $this->position = (int)$position;
            }
        }
    }

**Comment by andreyvk** [comment]
@emman-ok @smolinari i think a better solution would be to cast cluster and position into integer and then back to string again, since original ID cluster and position are strings initially

**Comment by smolinari** [comment]
Can the casting be avoided altogether?

Scott

**Comment by andreyvk** [comment]
@smolinari technically problem should be fixed somewhere before the `ID` is instantiated. It looks like some part of the code that deserializes RID passed from the server is initially casting it into a float or smth. Hence the problem with the floating point. After that ID is instantiated with a wrongly parsed `$position`. @emman-ok did not get rid or the problem, but prevented it from happening again. I personally think that the problem stems from `Reader::unpackLong`, but im not sure. @Ostico what do you think?

**Comment by Ostico** [comment]
Yes guys this is a bug that can happen in PHP 32bit version. @emman-ok can you confirm this?

By the way:
[ReadMe](https://github.com/Ostico/PhpOrient#in-phporient-by-design-numbers-are-always-treated-as-strings-because-of-the-platform-dependant-nature-of-php-in-32bit-platform-numbers-must-be-treated-as-string-because-values-greater-than-232-would-be-lost-and-the-bcmathgmp-modules-must-be-used-to-avoid-this-to-make-the-results-consistent-for-all-platforms--32-and-64bit--and-leave-to-the-userdeveloper-the-decision-on-how-to-use-its-own-data--by-manual-cast--strings-are-used-for-all-numeric-data-types)
